# Generated by Django 4.0.4 on 2022-05-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimeline',
            name='year',
            field=models.IntegerField(),
        ),
    ]
